"""empty message

Revision ID: 3712f8ebff21
Revises: f714c3d21010
Create Date: 2021-02-17 19:50:56.579831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3712f8ebff21'
down_revision = 'f714c3d21010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time', sa.Time(), nullable=True))
    op.create_index(op.f('ix_task_time'), 'task', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_time'), table_name='task')
    op.drop_column('task', 'time')
    # ### end Alembic commands ###
